# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DialogoSaludo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialogoSaludar(object):
    def setupUi(self, dialogoSaludar):
        dialogoSaludar.setObjectName("dialogoSaludar")
        dialogoSaludar.resize(320, 155)
        self.lbEscribaNombre = QtWidgets.QLabel(dialogoSaludar)
        self.lbEscribaNombre.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.lbEscribaNombre.setObjectName("lbEscribaNombre")
        self.txtNombre = QtWidgets.QLineEdit(dialogoSaludar)
        self.txtNombre.setGeometry(QtCore.QRect(140, 20, 161, 22))
        self.txtNombre.setObjectName("txtNombre")
        self.lbSaludo = QtWidgets.QLabel(dialogoSaludar)
        self.lbSaludo.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.lbSaludo.setObjectName("lbSaludo")
        self.lbMensajeSaludo = QtWidgets.QLabel(dialogoSaludar)
        self.lbMensajeSaludo.setGeometry(QtCore.QRect(140, 60, 161, 16))
        self.lbMensajeSaludo.setText("")
        self.lbMensajeSaludo.setObjectName("lbMensajeSaludo")
        self.btnSaludar = QtWidgets.QPushButton(dialogoSaludar)
        self.btnSaludar.setGeometry(QtCore.QRect(140, 100, 161, 28))
        self.btnSaludar.setObjectName("btnSaludar")

        self.retranslateUi(dialogoSaludar)
        QtCore.QMetaObject.connectSlotsByName(dialogoSaludar)

    def retranslateUi(self, dialogoSaludar):
        _translate = QtCore.QCoreApplication.translate
        dialogoSaludar.setWindowTitle(_translate("dialogoSaludar", "Saludo"))
        self.lbEscribaNombre.setText(_translate("dialogoSaludar", "Escriba su nombre:"))
        self.lbSaludo.setText(_translate("dialogoSaludar", "Saludo:"))
        self.btnSaludar.setText(_translate("dialogoSaludar", "Saludar"))
